### PR TITLE
Added sortable and sortableCallback props to VaTable. 

### PR DESCRIPTION
**Pull request by guastallaigor**
Updated TablesDocs and added new example for this prop.
This address #33 .

### CODE REVIEW

**Comment by guastallaigor** [comment]
I've done this where I work and it did work, I'm even using on my project there, but you're right, I just tried this at home and it didn't work, so I will try to check this tomorrow to see what's different here and there.

**Comment by guastallaigor** [comment]
Here it's working but I'm still investigating why doesn't work sometimes

**Demo:**

**Comment by damienix** [comment]
I reproduced when it doesn't work. It only works when I open the demo page with the tab already set to Tables. When I switch the tab, or reload on different and switch to Tables - sorting doesn't work. Can you take a look at that? Assuming you want to merge it of course :)

Cheers

**Comment by guastallaigor** [comment]
Allright, not sure why it's not working inside the framework in all cases :cry: 
So I will close this for now until I figure this one out.
Thank you for your time and I'm sorry for this.

**Pull request closed without merging**
