### PR TITLE
Custom rendering of Select2 options

### PR DESCRIPTION
**Pull request by guvial**
Set default value for formatResult and formatSelection properties of select2.
It is not obvious reading the code, but it allows you to customize rendering of your options with injection of html. 

Example of a color selector using select2 component:

HTML:
` 
<aui-select2-single id="xxxx-dialog-color" name="xxxx-dialog-color" v-model="xxxx.color.name">
       <aui-select2-option  v-for="color in colors" :value="color.name" :text="getColorOption(color.code)">
       </aui-select2-option>
</aui-select2-single>
`

JS:

`
getColorOption: function (colorCode) {
            return '<div class="holydev-calendar-color-option" style="background:' + colorCode + '"></div>'
}
`

N.B. If you do not use the formatSelection/formatResult properties of select2, your html is rendered as text. 

N.B. I have also tried to simply expose formatSelection/formatResult as properties in the vue component but it led to errors when you have multiple instances of select2 in the same DOM.

Link to closed PR that led to this one: https://github.com/spartez/vue-aui/pull/6

### CODE REVIEW

**Comment by damienix** [comment]
Hi, I played around with this concept of templating and finally came to move powerful templating using Vue scoped slots. I hope you are on a quite recent version of Vue. Can you check if this works for you? :)

https://github.com/spartez/vue-aui/releases/tag/v0.13.0

**Comment by guvial** [comment]
Hi Damian,
Yes, much more elegant indeed.
I will test it in my app and I will close the PR.
Thanks a lot !
Cheers

**Comment by damienix** [comment]
@guvial Please upgrade to v0.13.2 before testing as previous versions won't work correctly.

**Comment by guvial** [comment]
Hi Damian,
Thanks for this information, I am quite busy right now. Sure that I will test your latest version, thanks a lot. I will let you know ASAP. Cheers, 
Guillaume

**Pull request closed without merging**
